#
# Author:: AJ Christensen (<aj@junglist.gen.nz>)
# Copyright:: Copyright (c) 2012 AJ Christensen
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or#implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
require 'struct'
require 'celluloid'
require 'celluloid/group'
require 'celluloid/zmq'

class Pylon
  module Paxos

    class Command < Struct.new(:k, :cid, :op)
      # k is a serialized Pylon::Paxos::Client
      # serialized by the Client itself
      #
      # cid is a client request id, generated by the client
      #
      # op is a proc to run on the state
      # op *must* return a 2-tuple of state, result
    end

    class Consensus < Celluloid::Group
      supervise Pylon::Paxos::Replica, :as => :paxos_replica
      # supervise Pylon::Paxos::Acceptor, :as => :paxos_acceptor
      # supervise Pylon::Paxos::Commander, :as => :paxos_commander
      # supervise Pylon::Paxos::Scout, :as => :paxos_scout
      # supervise Pylon::Paxos::Leader, :as => :paxos_leader
    end

    class Client < Celluloid::Group
      supervise Pylon::Paxos::Client, :as => :paxos_client
    end

  end
end
